import type { ControlRow } from "./types";

export const DEMO_ROWS: ControlRow[] = [
  {
    tableIndex: 0,
    id: "DEM-001",
    provider: "AGRICULTOR DE PRUEBA 1",
    taxId: "00000000A",
    farm: "Finca Norte",
    municipality: "Murcia",
    crop: "Limón rodrejo",
    campaign: "2026",
    contractSigned: "Sí",
    contractStart: "2026-06-01",
    contractEnd: "2026-10-31",
    contractAlert: "VIGENTE",
    plannedCutDate: "2026-08-03",
    farmChecked: "Sí",
    fieldNotebook: "Sí",
    notebookReviewDate: "2026-07-30",
    analysisStatus: "Apto",
    analysisDate: "2026-07-29",
    certificateType: "ECO",
    certificateExpiry: "2026-12-31",
    otherDocuments: "Sí",
    reviewer: "Calidad",
    lastReviewDate: "2026-07-31",
    canHarvest: "SÍ",
    blockageReason: "",
    documentPath: "",
    otherAgreements: "Avisar 24 horas antes del corte.",
    cutStatus: "Sí",
    cutKgTotal: "18450",
    archived: "No",
    variety: "Rodrejo",
    expectedKg: "20000",
  },
  {
    tableIndex: 1,
    id: "DEM-002",
    provider: "AGRICULTOR DE PRUEBA 2",
    taxId: "00000000B",
    farm: "Parcela 18",
    municipality: "Molina de Segura",
    crop: "Limón fino",
    campaign: "2026",
    contractSigned: "Sí",
    contractStart: "2026-07-01",
    contractEnd: "2026-11-15",
    contractAlert: "VIGENTE",
    plannedCutDate: "2026-08-05",
    farmChecked: "Sí",
    fieldNotebook: "No",
    notebookReviewDate: "",
    analysisStatus: "Pendiente de revisión",
    analysisDate: "",
    certificateType: "Naturland",
    certificateExpiry: "2026-12-15",
    otherDocuments: "No aplica",
    reviewer: "",
    lastReviewDate: "",
    canHarvest: "NO",
    blockageReason: "Cuaderno de campo; Fecha revisión cuaderno; Análisis no apto o pendiente; Responsable; Fecha de revisión;",
    documentPath: "",
    otherAgreements: "",
    cutStatus: "No",
    cutKgTotal: "",
    archived: "No",
    variety: "Fino",
    expectedKg: "32000",
  },
  {
    tableIndex: 2,
    id: "DEM-003",
    provider: "AGRICULTOR DE PRUEBA 3",
    taxId: "00000000C",
    farm: "Finca Levante",
    municipality: "Orihuela",
    crop: "Limón eureka",
    campaign: "2026",
    contractSigned: "Sí",
    contractStart: "2026-05-15",
    contractEnd: "2026-08-10",
    contractAlert: "VENCE EN 10 DÍAS",
    plannedCutDate: "",
    farmChecked: "No",
    fieldNotebook: "Sí",
    notebookReviewDate: "2026-07-28",
    analysisStatus: "Apto",
    analysisDate: "2026-07-28",
    certificateType: "Demeter",
    certificateExpiry: "2027-01-31",
    otherDocuments: "Sí",
    reviewer: "Administración",
    lastReviewDate: "2026-07-30",
    canHarvest: "NO",
    blockageReason: "Fecha de corte prevista; Finca/parcela sin comprobar;",
    documentPath: "",
    otherAgreements: "Corte condicionado a confirmación de calibre.",
    cutStatus: "Sí",
    cutKgTotal: "12780",
    archived: "Sí",
    variety: "Eureka",
    expectedKg: "15000",
  },
];
