import type { ControlRow } from "./types";

function demoContractDetails(overrides: Record<string, string>) {
  return JSON.stringify({
    contractOrigin: "generated",
    buyerCompany: "TOÑIFRUIT, S.L.",
    signatureDate: "2026-07-15",
    contractNumber: "",
    sellerRepresentative: "Representante de demostración",
    sellerDni: "00000000T",
    sellerAddress: "Finca de demostración, Murcia",
    organicOperatorCode: "MU-DEMO/E",
    certifierCode: "CAAE-DEMO",
    ailimpoRegepaCode: "REG-DEMO",
    modality: "A KILOS",
    collectionBy: "Comprador",
    transportBy: "Comprador",
    pricePerKg: "0.45",
    totalPrice: "",
    ivaPercent: "12",
    irpfPercent: "2",
    advancePayment: "0",
    paymentDays: "30",
    insuranceProvider: "Agroseguro",
    insurancePolicy: "",
    applyDestrio: "No",
    destrioLocation: "",
    destrioDefects: "",
    destrioPrice: "",
    sellerEmail: "agricultor.demo@example.test",
    companyEmail: "compras.demo@example.test",
    buyerRepresentative: "Responsable de Compras",
    archiveId: "",
    archiveFilename: "",
    archivedAt: "",
    emailStatus: "pending_configuration",
    sellerSignedAt: "",
    buyerSignedAt: "",
    signatureMethod: "external_pending",
    ...overrides,
  });
}

function demoMaterials(items: Array<{ id: string; crop: string; variety: string; expectedKg: string; municipality: string; paraje: string; polygon: string; plot: string; hectares: string }>) {
  return JSON.stringify(items.map((item) => ({ ...item, situation: "Regadío" })));
}

export const DEMO_ROWS: ControlRow[] = [
  {
    tableIndex: 0,
    revision: "demo-0",
    id: "DEM-001",
    provider: "AGRICULTOR DE PRUEBA 1",
    taxId: "00000000A",
    farm: "Finca Norte",
    municipality: "Murcia",
    crop: "Limón",
    campaign: "2026",
    contractSigned: "Sí",
    contractStart: "2026-06-01",
    contractEnd: "2026-10-31",
    contractAlert: "VIGENTE",
    plannedCutDate: "2026-08-03",
    farmChecked: "Sí",
    fieldNotebook: "Sí",
    notebookReviewDate: "2026-07-30",
    analysisStatus: "Apto",
    analysisDate: "2026-07-29",
    certificateType: "ECO",
    certificateExpiry: "2026-12-31",
    otherDocuments: "Sí",
    reviewer: "Calidad",
    lastReviewDate: "2026-07-31",
    canHarvest: "SÍ",
    blockageReason: "",
    documentPath: "Biblioteca contractual privada: contrato-firmado-ton-demo-001.pdf",
    otherAgreements: "Avisar 24 horas antes del corte.",
    cutStatus: "Sí",
    cutKgTotal: "18450",
    archived: "No",
    variety: "Rodrejo",
    expectedKg: "20000",
    materialsJson: demoMaterials([
      { id: "dem-001-a", crop: "Limón", variety: "Rodrejo", expectedKg: "12000", municipality: "Murcia", paraje: "Finca Norte", polygon: "12", plot: "41", hectares: "1.25" },
      { id: "dem-001-b", crop: "Limón", variety: "Verna", expectedKg: "8000", municipality: "Murcia", paraje: "Finca Norte", polygon: "12", plot: "42", hectares: "0.80" },
    ]),
    registeredIca: "Sí",
    contractDetailsJson: demoContractDetails({
      contractOrigin: "existing",
      contractNumber: "TON-DEMO-001",
      archiveId: "demo-contract-ton-001",
      archiveFilename: "contrato-firmado-ton-demo-001.pdf",
      archivedAt: "2026-07-15T10:30:00.000Z",
      emailStatus: "sent",
      sellerSignedAt: "2026-07-15T10:00:00.000Z",
      buyerSignedAt: "2026-07-15T10:15:00.000Z",
      signatureMethod: "uploaded",
    }),
    recordStatus: "Activo",
    statusReason: "",
    statusUpdatedAt: "",
    statusUpdatedBy: "",
    statusHistoryJson: "",
  },
  {
    tableIndex: 1,
    revision: "demo-1",
    id: "DEM-002",
    provider: "AGRICULTOR DE PRUEBA 2",
    taxId: "00000000B",
    farm: "Parcela 18",
    municipality: "Molina de Segura",
    crop: "Mandarina + Clementina",
    campaign: "2026",
    contractSigned: "Pendiente de firma",
    contractStart: "2026-07-01",
    contractEnd: "2026-11-15",
    contractAlert: "VIGENTE",
    plannedCutDate: "2026-08-05",
    farmChecked: "Sí",
    fieldNotebook: "No",
    notebookReviewDate: "",
    analysisStatus: "Pendiente de revisión",
    analysisDate: "",
    certificateType: "Naturland; GRASP",
    certificateExpiry: "2026-12-15",
    otherDocuments: "No aplica",
    reviewer: "",
    lastReviewDate: "",
    canHarvest: "NO",
    blockageReason: "Cuaderno de campo; Fecha revisión cuaderno; Análisis no apto o pendiente; Responsable; Fecha de revisión;",
    documentPath: "",
    otherAgreements: "",
    cutStatus: "No",
    cutKgTotal: "",
    archived: "No",
    variety: "Nadorcott · Clemenules",
    expectedKg: "32000",
    materialsJson: demoMaterials([
      { id: "dem-002-a", crop: "Mandarina", variety: "Nadorcott", expectedKg: "18000", municipality: "Molina de Segura", paraje: "Parcela 18", polygon: "7", plot: "18", hectares: "1.60" },
      { id: "dem-002-b", crop: "Clementina", variety: "Clemenules", expectedKg: "14000", municipality: "Molina de Segura", paraje: "Parcela 18", polygon: "7", plot: "19", hectares: "1.20" },
    ]),
    registeredIca: "Sí",
    contractDetailsJson: demoContractDetails({
      buyerCompany: "MR. ORGÁNICA, S.L.",
      contractNumber: "MRO-DEMO-002",
      pricePerKg: "0.62",
    }),
    recordStatus: "Activo",
    statusReason: "",
    statusUpdatedAt: "",
    statusUpdatedBy: "",
    statusHistoryJson: "",
  },
  {
    tableIndex: 2,
    revision: "demo-2",
    id: "DEM-003",
    provider: "AGRICULTOR DE PRUEBA 3",
    taxId: "00000000C",
    farm: "Finca Levante",
    municipality: "Orihuela",
    crop: "Uva",
    campaign: "2026",
    contractSigned: "Sí",
    contractStart: "2026-05-15",
    contractEnd: "2026-08-10",
    contractAlert: "VENCE EN 10 DÍAS",
    plannedCutDate: "",
    farmChecked: "No",
    fieldNotebook: "Sí",
    notebookReviewDate: "2026-07-28",
    analysisStatus: "Apto",
    analysisDate: "2026-07-28",
    certificateType: "Demeter",
    certificateExpiry: "2027-01-31",
    otherDocuments: "Sí",
    reviewer: "Administración",
    lastReviewDate: "2026-07-30",
    canHarvest: "NO",
    blockageReason: "Fecha de corte prevista; Finca/parcela sin comprobar;",
    documentPath: "Biblioteca contractual privada: contrato-firmado-mro-demo-003.pdf",
    otherAgreements: "Corte condicionado a confirmación de calibre.",
    cutStatus: "Sí",
    cutKgTotal: "12780",
    archived: "Sí",
    variety: "Arra 19",
    expectedKg: "15000",
    materialsJson: demoMaterials([
      { id: "dem-003-a", crop: "Uva", variety: "Arra 19", expectedKg: "15000", municipality: "Orihuela", paraje: "Finca Levante", polygon: "5", plot: "73", hectares: "2.10" },
    ]),
    registeredIca: "No",
    contractDetailsJson: demoContractDetails({
      contractOrigin: "existing",
      buyerCompany: "MR. ORGÁNICA, S.L.",
      contractNumber: "MRO-DEMO-003",
      archiveId: "demo-contract-mro-003",
      archiveFilename: "contrato-firmado-mro-demo-003.pdf",
      archivedAt: "2026-05-15T09:00:00.000Z",
      emailStatus: "sent",
      sellerSignedAt: "2026-05-15T08:30:00.000Z",
      buyerSignedAt: "2026-05-15T08:45:00.000Z",
      signatureMethod: "uploaded",
      pricePerKg: "0.85",
    }),
    recordStatus: "Activo",
    statusReason: "",
    statusUpdatedAt: "",
    statusUpdatedBy: "",
    statusHistoryJson: "",
  },
];
